inherit_from:
  - .rubocop_airbnb.yml
LineLength:
  Max: 200
#検証除外フォルダ指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'config/credentials.yml.enc'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'app/helpers/*'
    - 'spec/rails_helper.rb'
    - 'spec/support/*'
