version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 300
      - run:
          name: データベースの作成
          command: docker-compose exec web rails db:create RAILS_ENV=test
      - run:
          name: データベースのセットアップ
          command: docker-compose exec web rails db:migrate RAILS_ENV=test
      - run:
          name: webコンテナ内に入る
          command: docker-compose run web bash
      - run:
          name: RSpecテスト実行
          command: bundle exec rspec
      - run:
          name: Rubocopテスト実行
          command: bundle exec rubocop
      - run:
          name: webコンテナから出る
          command: exit
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down
