version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    # CI環境上の circleci/classic の値の場所にGitリポジトリをコピーする
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: 'Dockerコンテナの起動を待機'
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose exec web bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          command: docker-compose exec web bundle exec bin/rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose exec web bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down
