version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: "10秒待機させる"
          command: sleep 10
      - run:
          name: データベースの作成
          command: docker-compose run web rails db:create RAILS_ENV=test
      - run:
          name: データベースのセットアップ
          command: docker-compose run web rails db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          command: |
            touch .env
            echo GURUNAVI_API_KEY=${GURUNAVI_API_KEY} > ~/.env
            docker-compose run web bundle exec rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose run web bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down
#   deploy:
#        machine:
#            image: circleci/classic:edge
#        steps:
#            - checkout
#            - add_ssh_keys:
#            - run: ssh ec2-user@18.177.212.209 'cd /var/www/rails/my_portfolio/ && git pull origin master'
#
# workflows:
#    version: 2
#    build_and_deploy:
#        jobs:
#            - build
#            - deploy:
#                requires:
#                    - build
#                filters:
#                    branches:
#                        only: master
